server:
  port: 9148
  servlet:
    context-path: /challenge

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/develop
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  liquibase:
    url: jdbc:postgresql://localhost:5432/develop
    user: admin
    password: admin123
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
  kafka:
    bootstrap-servers: localhost:9093
    admin:
      auto-create: true
    listener:
      concurrency: 1


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html

logging:
  level:
    root: info
    co.com.flypass: debug
    org.hibernate: info

management:
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics #${url_otlp}