KAFKA_BOOTSTRAP_SERVERS: pkc-xxxxx.us-central1.gcp.confluent.cloud:9092
KAFKA_USERNAME: <clave_api_confluent>
KAFKA_PASSWORD: <secreto_api_confluent>

TRUSTSTORE_PASSWORD: <truststore_pass>
KEYSTORE_PASSWORD: <keystore_pass>
KEY_PASSWORD: <key_pass>
