spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      security.protocol: SSL
      ssl.truststore.location: classpath:client.truststore.jks
      ssl.truststore.password: ${TRUSTSTORE_PASSWORD}
      ssl.keystore.location: classpath:client.keystore.jks
      ssl.keystore.password: ${KEYSTORE_PASSWORD}
      ssl.key.password: ${KEY_PASSWORD}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html
