#Para pruebas locales
receivers:
  otlp:
    protocols:
      http:
      grpc:
processors:
  # batch metrics before sending to reduce API usage
  batch:
exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: spring
extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
  pprof:
    endpoint: "0.0.0.0:1888"
  zpages:
    endpoint: "0.0.0.0:55679"
service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    # for now we only interested about metrics...
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
#    traces:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: [tempo]
#    logs:
#      receivers: [otlp]
#      exporters: [loki]pipoe